### ISSUE TITLE
Fail to retrieve contact list but Drive works fine - ConnectionRefusedError

### ISSUE THREAD

**Issue by nofno** [amonchakai/Hg10#108]
Hi,
I really like HG10 which is a great app. I use it with Hangout.
Since I have upgraded my Q10 to BB10 10.3.2, first HG10 has disappeared from the Hub. I tried to uninstall/reinstall it but the app won't connect to Hangout anymore. HG10 fails to retrieve my contact list (but keeps trying), while drive is working fine. Of course, upgrading to the last OS version might just be totally unrelated to the problem. 

In logs, a ConnectionRefusedError appears:

![img_20150915_215554](https://cloud.githubusercontent.com/assets/407060/9893967/f2d4cb8a-5bf4-11e5-8493-edd08d9f927e.png)

HG10 miss me... Do you have any idea about this issue?
Thanks a lot for your help.

**Comment by amonchakai** [comment]
Hi,

Sorry about that...

First, regarding the entry in the hub which disappear. I have to say I am aware of this, it is kinda systematic with all my apps... an OS update removes it, there are some API to restore it after an OS update, but it is kinda tricky to test/debug as OS updates does not append frequently. 

Regarding the connection issue, the error you see in the logs comes from the UI which cannot connect to the headless. I think I have an idea of what is happening. 

Could you try to remove Hg10, run 'account cleaner', delete the account for Hg10. There must be one from before the OS update. Then try again to reinstall the OS? (I know, it does not sound related, but if it is what I think, it is...)

If it does not work, you can go to the legacy section:
https://github.com/amonchakai/Hg10/releases/tag/1
And download the previous version: Hg10-1_4_1_186.bar
If that is what I think, this one should work.

And if you are willing to help, I could need some help to improve some error handling function I was trying to update with the last version. 

Thanks

**Comment by nofno** [comment]
Hi,

Thanks a lot for your help, hg10 is back.
For the record, what I exactly did is, in this order :
- uninstalling hg10
- removing all hg10 accounts with accounts cleaner (there were 2 of them)
- rebooting the device
- installing hg10 from BlackBerry world

If I can, I would be pleased to help. What kind of help do you need for the error handling? 

Thanks again.

**Comment by amonchakai** [comment]
Ok, that is great if it solved. 

I would have asked you to install some specific build to track down the bug, but now it is working fine with the version on the store, there is no error to track down. 

So enjoy, and I will try to dig into that issue by myself

Cheers
