### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by Tizzulat0r** [amonchakai/Hg10#111]
I'm using the latest version of Hg10 and in order to try and fix an older issue I uninstalled Hg10, deleted all of its data, and reinstalled it.

For whatever reason, after reinstalling, it will bring me to the Hg10 login screen. I can hit connect and scroll down to Request Permissions where it will bring me to a google page, logged in already where I can hit "allow" or "deny". I hit allow and it shows a spinning wheel at the top as well as the "Pinch out to stop filtering/Pull down to search a contact" stays on screen. If i swipe to the side, I can click on Drive and after almost a minute the contents of my Google Drive will actually show up. however switching back to Contacts it just spins indefinitely. I've let it sit here for about 10-15 minutes at the longest without quitting it and trying to start it again.

is this something i am doing wrong? i'm not sure if it's related, but I recently restored from a full backup I made of my Q10, and when I restored it my Google/android account seemed to be working fine but I did not go through the steps to set up an Android account again. My blackberry google device ID is still set and works.

I apologize if this isn't a Hg10 issue.

**Comment by amonchakai** [comment]
Hi,

I think you may need to try to
+ remove Hg10
+ get 'account cleaner': https://appworld.blackberry.com/webstore/content/59956050/
+ delete Hg10 entry(ies)
+ reinstall Hg10

The issue may be that there is a remaining hub account number for Hg10, and Hg10 is trying to restore it, but fails for some reason. So the headless is stuck trying to do this, and do not respond to other commands.

**Comment by Tizzulat0r** [comment]
Worked perfectly! Thank you a ton!
