### ISSUE TITLE
App no longer in blackberry world?

### ISSUE THREAD

**Issue by rdvl97** [amonchakai/Hg10#113]
Just got a blackberry passport and found that your app was no longer available for download. You can still access the store page on the BlackBerry world app if you have the direct link (still can't download it though), but if you try to access it within a Web browser It shows up for a split second then says that the page doesn't exist. :P Is it going to be brought back soon?  

Thanks in advance :)

**Comment by vapaavetehinen** [comment]
Just got it as well, and it appears in the store for me.

**Comment by rdvl97** [comment]
@vapaavetehinen ah, it appears its back now.  thanks :)  
ill close the issue now
