### ISSUE TITLE
message sync

### ISSUE THREAD

**Issue by vapaavetehinen** [amonchakai/Hg10#114]
When I open a conversation, the sync functionality syncs such that the most recent messages are from a while ago, January of this year. It always syncs such that that spot is the most recent, even though I have exchanged many messages since then. It does this (I think) every time the conversation refreshes. Any time you could dedicate to looking into this matter would be greatly appreciated!

EDIT: changed the time to be more accurate

**Comment by rdvl97** [comment]
I believe this is something that the google api does on its own as that's what happens with the google hangouts chrome extension as well.

**Comment by vapaavetehinen** [comment]
Hmmm. Just installed the chrome hangouts extension on windows to test it, and I am not getting the same error there. That said, I only use hangouts with one person, so perhaps I'll make another google account and chat with that account, for testing purposes.

**Comment by rdvl97** [comment]
which extension did you install?  the one that adds a green floating icon to your screen or the one that adds a button to the extensions pane?  I have the second one as it works better for my system.  Both versions function differently than eachother.

**Comment by vapaavetehinen** [comment]
The one that is part of the chrome app launcher and continues to run in the background. Looking at it in chrome, I see chrome identifies this as the app version, and the other is the extension version.

**Comment by rdvl97** [comment]
Sorry, I'm still a little confused.  Here's the one I'm using: https://chrome.google.com/webstore/detail/google-hangouts/nckgahadagoaajjgafhacjanaoiihapd

**Comment by vapaavetehinen** [comment]
that is not the one I just mentioned having installed, but I just switched over to it, uninstalling the other and installing that one, and that too functions normally.

it seems that only the one contact is affected. I'll see if I can find anything weird about the conversation.

**Comment by rdvl97** [comment]
welp, not much else i can do from here now.  I just updated to the latest version of BB10 and its broken hangouts \ hub integration.  :(  
so... yeah, dont update your device yet...

**Comment by vapaavetehinen** [comment]
what version are you on? I thought I was on the latest, and the hub integration part seems like it's still working for me.

**Comment by vapaavetehinen** [comment]
I'm on 10.3.2.2474

**Comment by rdvl97** [comment]
10.3.2.556 was just released

**Comment by vapaavetehinen** [comment]
I have the unlocked version, doesn't apply to me, as far as I can tell.

**Comment by rdvl97** [comment]
ah, well @amonchakai just figured out a workaround for it since he had the same issue: https://github.com/amonchakai/Hg10/issues/115

**Comment by vapaavetehinen** [comment]
Nice. In other news, I was completely wrong about the time-frame of what date it was pulling from. It's pulling a conversation from Jan 6th of this year,and I can't see anything weird when I look at the history around then.

**Comment by rdvl97** [comment]
How far back in your chat history do you really need to go?  If you need to reach back into the very beginning, why don't you just manually archive the chat record? https://support.google.com/hangouts/answer/3112142?hl=en

**Comment by vapaavetehinen** [comment]
Perhaps I did not properly explain my issue. I don't need to go back that far in the chat. However, when  I open the chat, that is exactly where it puts me, with this almost year old conversation as the most recent one, and I can't find the messages that are actually recent. if I send them, they stay until I refresh. If I receive them, I get a notification, and when I open the app, that message I received is the most recent for just a split second, and then it disappears, replaced by those same messages from January.

**Comment by amonchakai** [comment]
Maybe you could try to check from the gmail website what kind of reply hg10 gets from Google: type is:chat <contact email> 
In the search bar of gmail. It is basically what the app does

**Comment by amonchakai** [comment]
I meant is:chat email-addres-of-contact

**Comment by vapaavetehinen** [comment]
well, there are many results, the most recent of which is from the 6th of this month (Sunday) and they continue to go back in time, beyond the 6th of January this year, into 2014.

**Comment by amonchakai** [comment]
Ok. 

I have a beta with the ability to browse into the history. I will post a link to it later today. Maybe that will help to identify the problem

**Comment by vapaavetehinen** [comment]
Alright, so I went with the nuclear option, and deleted every chat I had with this contact, because as I mentioned above, I'm not to concerned with the conversation history. The issue is that now instead of going to some old chat, the view simply clears everything. I assume then that the issue before was not with those times overriding everything, but that somehow that conversation from January was the last one in a format the refresh function could find. So, now that it is gone, as is everything before it, there is now no chat that describes this. For whatever reason my chats with this contact are not getting stored in a way your application can retrieve them.

**Comment by vapaavetehinen** [comment]
I see that you have written elsewhere about how nicknames can be an issue. What does it mean for something to be a nickname? The name I have for the contact differs from that contact's G+ profile. Is that what is meant?

**Comment by amonchakai** [comment]
Ah, that would be it.

Yes, in some cases, when I receive the list of contacts I do not have the right email address for the contact but something which does not make sense like 
mdfigbaqm24klnerag13@public.talk.google.com

which is obviously not the right email, and then I can't use it to pull the history. So, I have to use another way: use the name of the contact to do the query. And if the name you can see in the application does not match to the real name of the user, then there is no chance to find with who you are talking to & synch the previous chat.

So, if that is the problem, you should just edit the name of your contact (context action in the list of contact) and edit the field "full name" by "first name last name" of your contact

**Comment by vapaavetehinen** [comment]
Fixed it. Thanks!
