### ISSUE TITLE
received messaged in chat window are not shown

### ISSUE THREAD

**Issue by sergzin** [amonchakai/Hg10#14]
I am chatting on Q10 with my jabber bot using generic xmpp server.
When I send message to bot it should immediately reply the same message back.
For some reason messages are not updated in chat window. 

I send messages to bot and see no replies.
![img_20150211_003006](https://cloud.githubusercontent.com/assets/2320021/6138947/6ac0f11a-b186-11e4-879d-8c42f23d7b68.png)

I exit the chat and open it again - messages are in order.
![img_20150211_003027](https://cloud.githubusercontent.com/assets/2320021/6138950/71dfe186-b186-11e4-965a-2510daf1d409.png)

**Comment by amonchakai** [comment]
Hi,
Thanks for reporting the bug. Could you check in the log if you can see in raw text what the bot is sending? (go to the settings, and there is a toggle for logs)
Apparently it is the dynamic rendering of the message which fails.

Thanks
