### ISSUE TITLE
Space between latest message and input box

### ISSUE THREAD

**Issue by BioTeckna** [amonchakai/Hg10#19]
On Q10 there is a display problem. Please see attachement.
There is a space between the latest message and the input box. This space's varies quite randomly.

![img_20150217_222132](https://cloud.githubusercontent.com/assets/3942982/6238592/461dc8d8-b6f4-11e4-908a-f94588fb773d.png)

**Comment by amonchakai** [comment]
Are you referring to this one? 
![461dc8d8-b6f4-11e4-908a-f94588fb773d](https://cloud.githubusercontent.com/assets/6967372/6244112/0f51f0a8-b74f-11e4-9021-30f838c134ab.png)

There is a minimum value for this space, so you can see the messages while typing. But that is it.

**Comment by kad6** [comment]
Yes, this is not cool at all. Looks and feels strange. Other apps don't have that space. When you show your keyboard the messages just move up. This is how it is supposed to work :)

**Comment by BioTeckna** [comment]
Yes, I'm speaking about this space. This look weird on my Q10

**Comment by amonchakai** [comment]
Ok, noted.
