### ISSUE TITLE
Text autocompletion not working

### ISSUE THREAD

**Issue by BioTeckna** [amonchakai/Hg10#20]
I am an active user of Hg10 and I will never thank you enough for creating such an app.
However I've notice BB10 autocompletion like "mypin", "hc" for the time, "dc" for the current date" and "bb" for BlackBerry isn't working in the app.

I've attached to this message an example of autocompletion working on bbm and not working in Hg10.

Thanks
![img_20150221_114804](https://cloud.githubusercontent.com/assets/3942982/6314075/4a83ae1e-b9c5-11e4-95ed-a4a4beb85adb.png)
![img_20150221_114808](https://cloud.githubusercontent.com/assets/3942982/6314076/4a83aedc-b9c5-11e4-9c4a-e442c9d9750d.png)

**Comment by amonchakai** [comment]
Hi,

Ok, noted. I will have a look.
It is strange because it is working on Z devices and Passport. But I have a slightly different UI for classic and Q devices. Maybe it broke something. 
I will check.

**Comment by amonchakai** [comment]
Ah no, it is not working either on my passport. Maybe there is an option I missed

**Comment by BioTeckna** [comment]
‎Ok :)                                                                                                                                                                                                                De: amonchakaiEnvoyé: dimanche 22 février 2015 12:40À: amonchakai/Hg10Répondre à: amonchakai/Hg10Cc: BioTecknaObjet: Re: [Hg10] Text autocompletion not working (#20)Ah no, it is not working either on my passport. Maybe there is an option I missed 

—Reply to this email directly or view it on GitHub.

**Comment by amonchakai** [comment]
not really sure of what I did, but it is now working in the last version

-> close
