### ISSUE TITLE
[REQUEST] Add OTR support to Hg10

### ISSUE THREAD

**Issue by stmblfrcr** [amonchakai/Hg10#23]
First of all - thank you for this! Great to have native Jabber on BB10. Is it possible to add otr/libotr support in the future? While your focus seems to be on Hangout, it would be cool to have this additional security as well. 

https://otr.cypherpunks.ca/

**Comment by amonchakai** [comment]
Hi,

I will have a look. Cannot promise anything, I am the only one working on this; cannot really go into every directions.

**Comment by stmblfrcr** [comment]
Totally understandable and thanks anyhow!

**Comment by Demorde** [comment]
I too would really enjoy this feature, as it goes now this is the only client I use that doesn't support it, making it the weakest link in my communication chain.

**Comment by amonchakai** [comment]
Added! :)

**Comment by stmblfrcr** [comment]
Awesome! Thanks :).
