### ISSUE TITLE
cannot connect to facebook

### ISSUE THREAD

**Issue by bertzi** [amonchakai/Hg10#24]
hi
first thanks for this great app.
And now my problem: im trying co connect to facebook but it doesent work. i dont know were exactly do the address (Host or Domain)? Could you please save the already written login data so that it isnt necessary to write the whole thing again if the connectection doesesnt work? 

regards

**Comment by amonchakai** [comment]
Hi,

You don't need to specify the Host & Domain. This will be resolved automatically by the application.
What you need to find is your jabber id. Previously, you could find it there: https://de-de.facebook.com/sitetour/chat.php

But now, it directly redirect to the messenger's page.... 

If you know it (something like "your user name"@chat.facebook.com ) you just need to enter it & your password. And that should work. If it does not, it is just Facebook which is blocking the app. You can check that in the security settings.  

Anyway, the XMPP service I am using will close soon: Facebook shutdown these server end of next month ( https://developers.facebook.com/docs/chat ). 

So I think, I will just remove all mention to Facebook. As there is no future for me to support it. 

Sorry.
