### ISSUE TITLE
Hub integration

### ISSUE THREAD

**Issue by Gh10User** [amonchakai/Hg10#36]
Hub integration is broken when uninstalled and installed again. By broken I mean that the application is not present in the hub.

**Comment by amonchakai** [comment]
Hi,

hum... did it disappeared after an uninstallation? 
Maybe could you check if there is a remaining account using this application: (Account cleaner on BBW)
https://appworld.blackberry.com/webstore/content/59956050/?lang=en

if so, try to delete it and reinstall the application. 

Hope that helps...

**Comment by Gh10User** [comment]
It helped, problem solved. Thanks
