### ISSUE TITLE
BlackBerry q 10 message screen does not fit

### ISSUE THREAD

**Issue by Gh10User** [amonchakai/Hg10#38]
On BlackBerry q10 message screen does not fit on display.

**Comment by amonchakai** [comment]
On a Q10, the interface is supposed to be like this:

![capture d ecran 2015-04-29 a 08 50 11](https://cloud.githubusercontent.com/assets/6967372/7385850/ce90dc16-ee4c-11e4-9f28-5533406de880.png)

Do you have something different?
