### ISSUE TITLE
No buddies displayed for generic XMPP server

### ISSUE THREAD

**Issue by excelangue** [amonchakai/Hg10#5]
Hi,

I try logging in with the AdvancedLogin panel with:
Host: (auto)
Domain: (auto)
Port: (auto)
User: excel@jabber.de

It goes to an empty contacts list with a spinning circle. Contacts I add from the app appear in my other client's buddy list, but no contacts are ever shown in the app.

**Comment by excelangue** [comment]
![img_20150112_224207](https://cloud.githubusercontent.com/assets/4421576/5716940/bec57ae2-9aac-11e4-8575-5b2ede6a6b2c.png)
![img_20150112_224231](https://cloud.githubusercontent.com/assets/4421576/5716941/bedfe3f0-9aac-11e4-8009-eac9855f5272.png)

**Comment by amonchakai** [comment]
Hi, 
Thanks for reporting the issue. I will have a look to see what is going on...

**Comment by amonchakai** [comment]
OK, it should be fixed. 
If you want to try, you can side load this version: 
https://github.com/amonchakai/Hg10/releases/tag/1

I will push it to the store at the end of the month.
