### ISSUE TITLE
bug: Unable to Submit Issues from App Itself

### ISSUE THREAD

**Issue by MagnusOxlund** [amonchakai/Hg10#56]
Trying to submit a new bug, enhancement, or question via the established method in the Hg10 app itself fails. 

After having composed the post, having tapped "post" on the top right corner, and having accepted the confirmation prompt, the user is returned to the composition stage without the message having been posted under the respective category. The message still appears in the text input field, but the message will not appear as an issue.

No error message is displayed.

This is not the case for replies to other posts already appearing on the respective board, e.g., bug reports; the composition window closes and the post immediately appears as a reply as expected.

This bug has been observed on a BlackBerry Q10, running BB10 version 10.3.1.1779.

**Comment by amonchakai** [comment]
Hum... Ok
I will check what is happening. 

Thanks for reporting the issue.

**Comment by amonchakai** [comment]
apparently it is working again...

**Comment by MagnusOxlund** [comment]
I'm still experiencing this issue. Have you tried from a Q10?

**Comment by amonchakai** [comment]
The type of phone is irrelevant, the differences between devices are only cosmetics. And for this part, there is not even differences at all. 
In general it works, I think it is github which does not like to have the same user (Gh10User) having too many different IPs.
