### ISSUE TITLE
Enhancement: Improve Text Input Field

### ISSUE THREAD

**Issue by MagnusOxlund** [amonchakai/Hg10#57]
First off, I enjoy the privilege it is to have Hangouts made freely available on BB10 by an independent developer, so thank you for making that possible.

The text input field spans just two relatively short lines of text, which make up roughly two thirds of the width of the screen. Additionally, the text input field is partly hidden when entering a conversation, and is not selected by default. For this reason, it has to be fetched, by either scrolling down or tapping the visible half of the text input field, and selected manually before you can begin typing as the text input field is not selected by default when entering a conversation.

I find that this makes it difficult to review and edit messages, especially longer ones, before sending them and leaves room for improvement of the user experience. 

Here are my suggestions:

* Enlarge the text input field vertically to cover a significant portion of the screen.

 * Consider increasing the vertical size of the text input field as more lines of text are typed in until a max. amount of lines are met, e.g., 3 lines, then start scrolling the text input as even more lines are added. WhatsApp for BB10 does this, which works very well in my experience.

 * Consider moving the actions/smiley button to the right of the text input field so it is horizontally centered on the screen.

* Select the text input field by default when entering a conversation so you can begin typing without having to select the field first.

* Avoid hiding the text input field. A possible exception would be when scrolling up through previous messages.
 * Consider eliminating the blank space left between the latest message and the text input field. This will allow the user to read more of the recent conversation without having to scroll up to see it. 

Thank you for reading my suggestions.

**Comment by amonchakai** [comment]
Hi,

Thanks for the feedback. 

As I don't have a Q10, I have to admit that my tests are restricted to what I can see in the virtual machine. So I may have missed few things. 

I will restart working on this in the next days. There is really a long list of things to do, so it may take some time. But I will work on improving these things. I will have a look to whatsapp see if I can catch some good idea. 

Best

**Comment by MagnusOxlund** [comment]
That sounds great. 

You're welcome to ask me for screenshots or other feedback if you don't have other means for viewing it on a Q10. 

I would be glad to help in any way I'm able to.

**Comment by Gh10User** [comment]
Will do :)                                                                                                                                                                                                                                                                                                                                                      From: MagnusOxlundSent: Tuesday, June 2, 2015 20:58To: amonchakai/Hg10Reply To: amonchakai/Hg10Subject: Re: [Hg10] Enhancement: Improve Text Input Field (#57)That sounds great. 

You're welcome to ask me for screenshots or other feedback if you don't have other means for viewing it on a Q10. 

I would be glad to help in any way I'm able to. 

—Reply to this email directly or view it on GitHub.

**Comment by amonchakai** [comment]
Hello,

I made some general improvement all over the app. If you want to have a look, you can find a build there:
https://github.com/amonchakai/Hg10/releases/tag/1.3

Thanks for the feedback!

**Comment by MagnusOxlund** [comment]
Hi,Thanks for letting me know. Have you submitted it to BlackBerry World, or does it have to be installed manually?Best,Magnus                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: amonchakaiSent: Thursday, June 11, 2015 21:20To: amonchakai/Hg10Reply To: amonchakai/Hg10Cc: MagnusOxlundSubject: Re: [Hg10] Enhancement: Improve Text Input Field (#57)Hello,

I made some general improvement all over the app. If you want to have a look, you can find a build there:
https://github.com/amonchakai/Hg10/releases/tag/1.3

Thanks for the feedback!

—Reply to this email directly or view it on GitHub.

**Comment by amonchakai** [comment]
It is not submitted yet. 

I will most likely do that during the week-end, and it will be available at some point next week.

**Comment by MagnusOxlund** [comment]
Okay. I'm looking forward to check it out.

Sent from my BlackBerry 10 smartphone.
From: amonchakai
Sent: Thursday, June 11, 2015 22:14
To: amonchakai/Hg10
Reply To: amonchakai/Hg10
Cc: MagnusOxlund
Subject: Re: [Hg10] Enhancement: Improve Text Input Field (#57)


It is not submitted yet.

I will most likely do that during the week-end, and it will be available at some point next week.

---

**Comment by MagnusOxlund** [comment]
Hi again,I have been trying out the new version of Hg10 the past few days. Sorry it took a while; I don't have that many contacts on Hangouts to test the app with. I like the updated conversation layout. It's easier to write a message and to keep track of the conversation without breaking the flow now that you don't have to scroll as much. I also like the feature that sent/received messages are color-coded, and the centered text field looks nice. There are still some issues with messages disappearing, and editing and scrolling in the input field could still be improved, but it's nice to have an update. Let me know if you want some more feedback.Again, thanks for making the app. Sincerely,Magnus                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: amonchakaiSent: Thursday, June 11, 2015 22:14To: amonchakai/Hg10Reply To: amonchakai/Hg10Cc: MagnusOxlundSubject: Re: [Hg10] Enhancement: Improve Text Input Field (#57)It is not submitted yet. 

I will most likely do that during the week-end, and it will be available at some point next week. 

—Reply to this email directly or view it on GitHub.

**Comment by amonchakai** [comment]
I was aware it was still not great, but I needed to sleep over it to find a solution. 
So I published it like this.

But I think the new version available on the store from today is now good. 
So for me, this issue is closed.
