### ISSUE TITLE
version in Blackberry World

### ISSUE THREAD

**Issue by z3rogate** [amonchakai/Hg10#63]
Hello Dev.-Team,

first of all thank you for you great work! Keep up the good work!
Is the version in Blackberry World is the latest one ? If no is there an "Beta" i can Test for you ?

regards Richard

**Comment by amonchakai** [comment]
Not yet, there is a beta, but it fixes bugs you may not have experienced (they was some problem when you have a long list of contacts).

And the OTR stuff is not yet integrated. I made big progress, but it is not finished.

**Comment by z3rogate** [comment]
THX
