### ISSUE TITLE
Message Sync Problem

### ISSUE THREAD

**Issue by steinbrueckri** [amonchakai/Hg10#64]
Hello Dev.-Team,

i have an problem with the message sync. when i receive an message, the last messege in the conversation will show in the Hub. At this point all is fine. But when i open the Conversation hg10 is starting and the messege i'm receive 2 sec ago will show up and in the next moment (i think the message sync is trigger) the conversation will  overwrite with the conversation of an other user.

regards Richard

**Comment by amonchakai** [comment]
Hi,

I am not sure to have understood, this happens when you change quickly from one person to another? 

Or with just one person, when you open the conversation in the hub, it load an unrelated conversation? 
If that is the second case, did you have a group chat with that person (using another client) ? 
Is his name somehow related to yours?

**Comment by z3rogate** [comment]
>I am not sure to have understood, this happens when you change quickly from one person to >another?
No ...

>Or with just one person, when you open the conversation in the hub, it load an unrelated >conversation? 
it open an conversation with "Bob" but the message in the conversation is from "Tom" to me.

>If that is the second case, did you have a group chat with that person (using another client) ? 
>Is his name somehow related to yours?
In our team, every body is using hangout with the Desktop client or with the phone (Android or iOS).
and yes i have an open group chat in my Desktop Client.

sorry for my bad english ... ;)

**Comment by amonchakai** [comment]
I see, I guessed you had a group chat with that person and you are receiving messages from another person who was in that group chat. 

I will try to improve that

**Comment by amonchakai** [comment]
Hello,

Do you frequently encounter this issue? 
Would you would be willing to try a beta, and tell me if this solve the problem ?

It is there:
https://github.com/amonchakai/Hg10/releases/tag/1.3

It also add the support for the images sent by people using the iOS/android google hangouts. :)
