### ISSUE TITLE
Using the fox for the hug message icon

### ISSUE THREAD

**Issue by Gh10User** [amonchakai/Hg10#70]
The square flag currently used for the hub message icon doesn't fit in with the rest of the theme of Hg10. Maybe using the fox icon would be more in line with the design aesthetic of the application?

**Comment by amonchakai** [comment]
Ah, why not! 

I will give it a try to see how it looks

**Comment by Gh10User** [comment]
This!

**Comment by amonchakai** [comment]
done.
