### ISSUE TITLE
How to set up an arbitrary XMPP account?

### ISSUE THREAD

**Issue by dryo** [amonchakai/Hg10#89]
This is more a question than a bug report. As I could not find any documentation on how to do it i'll ask here:

I installed Hg10 on two blackberries Q10 and can't find any other option than to log in with a google account. I don't have or want a google account. Where am I supposed to put my XMPP login credentials? Is it the screen size?

**Comment by amonchakai** [comment]
You can find it on the first screen when the application start.
You have to tap on the icon on the top right.

Everything is independent of the screen size. It works on Q10.

**Comment by dryo** [comment]
Hm. Seems to be an ID-10T error, then. :D

Funny. 2 friends of mine also had this ID-10T error because they thought the input fields are sub menus and were puzzled that nothing happened when tapping them. So maybe the layout should be more clear. Normally we aren't that kind of user that are the problem. ;)

Close?

**Comment by amonchakai** [comment]
Maybe :p

OK, I may have sacrified the readability for aesthetic... 
I will check it
